server:
  port: 8082
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/huobi?serverTimezone=Asia/Shanghai&zeroDateTimeBehavior=convertToNull&autoReconnect=true&useSSL=false&failOverReadOnly=false&allowPublicKeyRetrieval=true
    username: root
    password: chenchao
    type: com.zaxxer.hikari.HikariDataSource
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  #  mail:
#    host: smtp.163.com
#    username: 13065189401@163.com
#    password: CHEN4419
#    port: 25
  jackson:
    date-format: java.text.SimpleDateFormat
    time-zone: GMT+8
  mail:
    host: smtp.163.com
    password: KBBVNQVCPUTZYNTO
    username: 13065189401@163.com
    port: 25
    default-encoding: UTF-8
  #    host: smtp.gmail.com
#    username: shaoshuai2028@gmail.com
#    password: shaoSHAI123
#    protocol: smtp
#    default-encoding: utf-8
#    from: shaoshuai2028@gmail.com
#    properties:
#      mail:
#        smtp:
#          auth: true
#          port: 465
#          starttls:
#            enable: true
#            required: true
#          ssl:
#            enable: true
#        dispaly:
#          sendmail: shaoshuai2028@gmail.com
#          sendname: sendname
  thymeleaf:
    cache: false
    suffix: .html
    prefix: classpath:/templates/
    encoding: UTF-8
mess:
  from: ${spring.mail.username}
  to: ${spring.mail.username}
  #,1179552827@qq.com,gleader002@126.com,15313524729@163.com,okehanzhao@hotmail.com,398073582@qq.com,lin@swft.pro


