spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/huobi?serverTimezone=Asia/Shanghai&zeroDateTimeBehavior=convertToNull&autoReconnect=true&useSSL=false&failOverReadOnly=false
    username: root
    password: chenchao
    type: com.zaxxer.hikari.HikariDataSource
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  mail:
    host: smtp.163.com
    username: 13065189401@163.com
    password: CHEN4419
    port: 25
  jackson:
    date-format: java.text.SimpleDateFormat
    time-zone: GMT+8
mess:
  from: ${spring.mail.username}
  to: ${spring.mail.username},gleader002@126.com

